name: "Build MySQL"
on:
  workflow_dispatch:
    inputs:
      mysql-versions:
        description: MySQL versions to build (JSON Array)
        required: true
        default: ""

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          {
            echo "suffix=$(date +%Y%m%d%H%M%S)"
            echo "matrix-releases=$(printenv MYSQL_VERSIONS | jq -c '{mysql: .}')"
            echo "matrix-linux=$(printenv MYSQL_VERSIONS | jq -c '{mysql: . , os: ["ubuntu-24.04", "ubuntu-22.04", "ubuntu-24.04-arm", "ubuntu-22.04-arm"]}')"
            echo "matrix-darwin=$(printenv MYSQL_VERSIONS | jq -c '{mysql: ., os: ["macos-15-intel", "macos-14"]}')"
            echo "matrix-windows=$(printenv MYSQL_VERSIONS | jq -c '{mysql: .}')"
          } >> "$GITHUB_OUTPUT"
        env:
          MYSQL_VERSIONS: ${{ github.event.inputs.mysql-versions }}
    outputs:
      suffix: ${{ steps.set-matrix.outputs.suffix }}
      matrix-releases: ${{ steps.set-matrix.outputs.matrix-releases }}
      matrix-linux: ${{ steps.set-matrix.outputs.matrix-linux }}
      matrix-darwin: ${{ steps.set-matrix.outputs.matrix-darwin }}
      matrix-windows: ${{ steps.set-matrix.outputs.matrix-windows }}

  create-releases:
    runs-on: ubuntu-latest
    needs: list
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list.outputs.matrix-releases) }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: create release
        run: |
          gh release create "mysql-$MYSQL_VERSION-$SUFFIX" --draft --title "MySQL $MYSQL_VERSION" --notes "MySQL $MYSQL_VERSION built by shogo82148/build-mysql"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
          SUFFIX: ${{ needs.list.outputs.suffix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ${{ matrix.os}}
    needs: [list, create-releases]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list.outputs.matrix-linux) }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: build MySQL
        run: ./build-mysql-linux.sh "$MYSQL_VERSION"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
      - name: upload
        run: |
          case "$(uname -m)" in
              "x86_64")
                  MYSQL_ARCH="x64"
                  ;;
              "arm64" | "aarch64")
                  MYSQL_ARCH="arm64"
                  ;;
              *)
                  echo "unsupported architecture: $(uname -m)"
                  exit 1
                  ;;
          esac
          mv "$RUNNER_TEMP/mysql.tar.zstd" "$RUNNER_TEMP/mysql-$MYSQL_VERSION-${BUILD_OS%-arm}-$MYSQL_ARCH.tar.zstd"
          gh release upload "mysql-$MYSQL_VERSION-$SUFFIX" "$RUNNER_TEMP/mysql-$MYSQL_VERSION-${BUILD_OS%-arm}-$MYSQL_ARCH.tar.zstd"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
          BUILD_OS: ${{ matrix.os }}
          SUFFIX: ${{ needs.list.outputs.suffix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: attest-build-provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: ${{ runner.temp }}/*.tar.zstd

  build-darwin:
    runs-on: ${{ matrix.os}}
    needs: [list, create-releases]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list.outputs.matrix-darwin) }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: install bison
        run: |
          # pre-installed version is too old.
          # install new one.
          brew install bison
      - name: build MySQL
        run: ./build-mysql-darwin.sh "$MYSQL_VERSION"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
      - name: upload
        run: |
          case "$(uname -m)" in
              "x86_64")
                  MYSQL_ARCH="x64"
                  ;;
              "arm64" | "aarch64")
                  MYSQL_ARCH="arm64"
                  ;;
              *)
                  echo "unsupported architecture: $(uname -m)"
                  exit 1
                  ;;
          esac
          mv "$RUNNER_TEMP/mysql.tar.zstd" "$RUNNER_TEMP/mysql-$MYSQL_VERSION-darwin-$MYSQL_ARCH.tar.zstd"
          gh release upload "mysql-$MYSQL_VERSION-$SUFFIX" "$RUNNER_TEMP/mysql-$MYSQL_VERSION-darwin-$MYSQL_ARCH.tar.zstd"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
          SUFFIX: ${{ needs.list.outputs.suffix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: attest-build-provenance
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: ${{ runner.temp }}/*.tar.zstd

  build-windows:
    runs-on: windows-2022
    needs: [list, create-releases]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list.outputs.matrix-windows) }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: build MySQL
        run: .\build-mysql-windows.ps1 $env:MYSQL_VERSION
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
      - name: upload
        shell: bash
        run: |
          TEMP_DIR=$(cygpath "C:\\Temp")
          mv "$TEMP_DIR/mysql.zip" "$TEMP_DIR/mysql-$MYSQL_VERSION-win32-x64.zip"
          gh release upload "mysql-$MYSQL_VERSION-$SUFFIX" "$TEMP_DIR/mysql-$MYSQL_VERSION-win32-x64.zip"
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
          SUFFIX: ${{ needs.list.outputs.suffix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: C:\Temp\*.zip

  publish-releases:
    runs-on: ubuntu-latest
    needs: [list, build-linux, build-darwin, build-windows]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list.outputs.matrix-releases) }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: publish release
        run: |
          gh release edit "mysql-$MYSQL_VERSION-$SUFFIX" --draft=false
        env:
          MYSQL_VERSION: ${{ matrix.mysql }}
          SUFFIX: ${{ needs.list.outputs.suffix }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
